version: '3.9'

x-cloudant-vars: &cloudant_vars
    CLOUDANT_APIKEY: ${CLOUDANT_APIKEY}
    CLOUDANT_URL: ${CLOUDANT_URL}
    CLOUDANT_USERNAME: ${CLOUDANT_USERNAME}
    CLOUDANT_PASSWORD: ${CLOUDANT_PASSWORD}

x-cos-vars: &cos_vars
    COS_BUCKET_NAME: ${COS_BUCKET_NAME}
    COS_API_KEY: ${COS_API_KEY}
    COS_ENDPOINT: ${COS_ENDPOINT}
    COS_INSTANCE_ID: ${COS_INSTANCE_ID}

x-cron-vars: &cron_vars
    MONTHLY_BACKUP_SCHEDULE: ${MONTHLY_BACKUP_SCHEDULE}
    DAILY_BACKUP_SCHEDULE: ${DAILY_BACKUP_SCHEDULE}

services:
    cloudant-backup-service:
        build:
            context: .
            dockerfile: Dockerfile.dev
        container_name: cloudant-backup-service
        hostname: cloudant-backup-service.local
        image: cloudant-backup-service:latest
        platform: linux/amd64
        environment:
            <<:
              [
                  *cloudant_vars,
                  *cos_vars,
                  *cron_vars
              ]
        volumes:
            - ./.env:/code/.env
